uploads = []
generated = []

[[outputs]]
id = "JFSKBXBHyfOgD9HG1dc2X"
uri = "file://dist-cpanel.tar.gz"
type = "unspecified"
title = "CA Aspire BD — Updated cPanel Frontend"

[[outputs]]
id = "nRFWBcxv4tPAx2k2LRl2o"
uri = "file://dist.tar.gz"
type = "unspecified"
title = "dist.tar.gz — Frontend Production Build (with auth fixes)"
